### ISSUE TITLE
Spalte auf bestimmte Breite beschränken

### ISSUE THREAD

**Issue by christlang** [christlang/parcelTracking#2]
Was stört an der dynamischen Platzeinteilung?
Können dadurch andere Dinge nicht richtig gelesen werden?

**Comment by markneuf** [comment]
Aktuell, stört es nicht wirklich. Bisher können alle Dinge gelesen werden. Wäre aktuell nur eine Sache fürs Auge.

**Comment by christlang** [comment]
Wie würdest Du die Aufteilung denn haben wollen? Habe da im Kopf dass zur Zeit der Platz dynamisch zugewiesen wird und damit für jede Auflösung (Computer / Handy / Tablett) eine nutzbare Tabelle raus kommt. Wenn ich feste Werte angebe, dann würde das auf manchen Geräten gut aussehen auf anderen wieder nicht.

Stört Dich denn, dass die Spalte zu lang ist und man den Kommentar dann schlecht lesen kann. Willst Du den Kommentar formatiert eingeben, also mit Zeilenumbrüchen und so was?

**Comment by markneuf** [comment]
Das die Spaltenbreite dynamisch ist und damit auf allen Geräten eine nutzbare Tabelle rauskommt ist natürlich schon von Vorteil.
Aktuell habe ich noch nicht wirklich mit den Kommentaren gearbeitet und weiß auch nicht wie oft ich das brauche und wie groß die dann werden, daher würde ich sagen lassen wir es einfach, erst einmal so.

**Comment by christlang** [comment]
bei Bedarf wieder öffnen
